name: ElysiumItem
version: 1.0.0
main: dev.elysium.item.ElysiumItem
api-version: '1.21'
authors:
  - Elysium
description: Special Items - Build Fragments System

depend:
  - ElysiumCore

commands:
  eitem:
    description: ElysiumItem player command
    aliases: [ei]
    usage: /eitem <info|list>
    permission: elysium.item.use
  eitemadmin:
    description: ElysiumItem admin command
    aliases: [eia]
    usage: /eitemadmin <give|list|gui>
    permission: elysium.item.admin

  trangbi:
    description: Mo GUI trang bi phu kien
    usage: /trangbi
    permission: elysium.item.use

  loren:
    description: Mo GUI Lo Ren (Kham Ngoc, Nang Cap)
    usage: /loren
    permission: elysium.item.use

permissions:
  elysium.item.use:
    default: true
  elysium.item.admin:
    default: op
